In [1]:
import sys
sys.path.append('..')

# Lurie-Goldberg Algorithm

In [2]:
import scipy_psdm as psdm
import numpy as np

# A matrix with subjectively set correlations
mat = [[ 1.   , -0.948,  0.099, -0.129],
       [-0.948,  1.   , -0.591,  0.239],
       [ 0.099, -0.591,  1.   ,  0.058],
       [-0.129,  0.239,  0.058,  1.   ]]
mat = np.array(mat)

# Convert to a positive semi-definite matrix
rho = psdm.luriegold(mat)
print(rho.round(3))

[[ 1.    -0.884  0.128 -0.138]
 [-0.884  1.    -0.555  0.228]
 [ 0.128 -0.555  1.     0.053]
 [-0.138  0.228  0.053  1.   ]]


In [3]:
np.allclose(np.diag(rho), 1.0)

True

In [4]:
# difference
print(np.abs(mat - rho).round(3))

[[0.    0.064 0.029 0.009]
 [0.064 0.    0.036 0.011]
 [0.029 0.036 0.    0.005]
 [0.009 0.011 0.005 0.   ]]


# Generate correlated random numbers

In [5]:
X, rho = psdm.randcorr(n_obs=100, n_vars=5, random_state=42)
print(rho.round(3))

[[ 1.     0.726  0.6    0.286 -0.524]
 [ 0.726  1.     0.508  0.056  0.146]
 [ 0.6    0.508  1.    -0.462 -0.426]
 [ 0.286  0.056 -0.462  1.    -0.281]
 [-0.524  0.146 -0.426 -0.281  1.   ]]


In [6]:
print(np.corrcoef(X, rowvar=False).round(3))

[[ 1.     0.761  0.572  0.397 -0.555]
 [ 0.761  1.     0.522  0.163  0.05 ]
 [ 0.572  0.522  1.    -0.373 -0.438]
 [ 0.397  0.163 -0.373  1.    -0.35 ]
 [-0.555  0.05  -0.438 -0.35   1.   ]]
