In [1]:
import sys
sys.path.append('..')

# Lurie-Goldberg Algorithm

In [2]:
import scipy_psdm as psdm
import numpy as np

# A matrix with subjectively set correlations
mat = [[ 1.   , -0.948,  0.099, -0.129],
       [-0.948,  1.   , -0.591,  0.239],
       [ 0.099, -0.591,  1.   ,  0.058],
       [-0.129,  0.239,  0.058,  1.   ]]
mat = np.array(mat)

# Convert to a positive semi-definite matrix
rho = psdm.luriegold(mat)
print(rho.round(3))

[[ 1.    -0.885  0.128 -0.138]
 [-0.885  1.    -0.555  0.228]
 [ 0.128 -0.555  1.     0.053]
 [-0.138  0.228  0.053  1.   ]]


In [3]:
np.allclose(np.diag(rho), 1.0)

True

In [4]:
# difference
print(np.abs(mat - rho).round(3))

[[0.    0.063 0.029 0.009]
 [0.063 0.    0.036 0.011]
 [0.029 0.036 0.    0.005]
 [0.009 0.011 0.005 0.   ]]
